<?php

namespace AppBundle\Repository;

/**
 * EternityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EternityRepository extends \Doctrine\ORM\EntityRepository
{
}
