# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.app_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    app.eternity_api:
          class: AppBundle\Service\EternityApiService
          arguments: ["@doctrine.orm.entity_manager","@service_container"]
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    admin.eternity:
          class: AppBundle\Admin\EternityAdmin  #Snd\EternityBundle\Admin\Hipay_subModelAdmin
          arguments: [~,  AppBundle\Entity\Eternity , ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: Eternity, group: Grc plateform }
          public: true
    admin.ticket:
          class: AppBundle\Admin\TicketAdmin
          arguments: [~, AppBundle\Entity\Ticket , ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: Tickets, group: Grc plateform }
          public: true
    admin.user:
          class: AppBundle\Admin\UserAdmin
          arguments: [~, AppBundle\Entity\User , ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: Grc Users, group: Grc plateform }
          public: true
